project_id = "vrmvvjfpfqqinuqagjdx"

[functions.create-payment]
verify_jwt = false

[functions.generate-portraits]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.download-portrait]
verify_jwt = false
